backend:
  name: github
  repo: ATFBMX/atfbmx.github.io
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "riders"
    label: "Riders"
    folder: "_data"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Instagram Link", name: "instagram", widget: "string", required: false}
